services:
  - type: web
    name: springboot-boilerplate
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-bold-voice-a4yp8xc9-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: default
      - key: SPRING_DATASOURCE_PASSWORD
        value: z9GYTlrXa8Qx