
    create table microposts (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        content varchar(140) not null,
        picture varchar(255),
        primary key (id)
    );

    create table password_reset_tokens (
        expiry_date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null unique,
        token varchar(255),
        primary key (id)
    );

    create table relationships (
        created_at timestamp(6),
        followed_id bigint not null,
        follower_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        primary key (id)
    );

    create table users (
        activated boolean,
        admin boolean not null,
        activation_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        refresh_token_expiration_at timestamp(6),
        reset_sent_at timestamp(6),
        updated_at timestamp(6),
        name varchar(50) not null,
        activation_digest varchar(255),
        email varchar(255) not null unique,
        password varchar(255) not null,
        refresh_token varchar(255),
        remember_digest varchar(255),
        reset_digest varchar(255),
        primary key (id)
    );

    alter table if exists microposts 
       add constraint FKpdw01oqg7mb3i9rac2mbu4yrg 
       foreign key (user_id) 
       references users;

    alter table if exists password_reset_tokens 
       add constraint FKk3ndxg5xp6v7wd4gjyusp15gq 
       foreign key (user_id) 
       references users;

    alter table if exists relationships 
       add constraint FKixqgg0x8a5p2totfqe73bsqxm 
       foreign key (followed_id) 
       references users;

    alter table if exists relationships 
       add constraint FKem49n8xoiecjatiff5oiiyn4v 
       foreign key (follower_id) 
       references users;

    create table microposts (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        content varchar(140) not null,
        picture varchar(255),
        primary key (id)
    );

    create table password_reset_tokens (
        expiry_date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null unique,
        token varchar(255),
        primary key (id)
    );

    create table relationships (
        created_at timestamp(6),
        followed_id bigint not null,
        follower_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        primary key (id)
    );

    create table users (
        activated boolean,
        admin boolean not null,
        activation_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        refresh_token_expiration_at timestamp(6),
        reset_sent_at timestamp(6),
        updated_at timestamp(6),
        name varchar(50) not null,
        activation_digest varchar(255),
        email varchar(255) not null unique,
        password varchar(255) not null,
        refresh_token varchar(255),
        remember_digest varchar(255),
        reset_digest varchar(255),
        primary key (id)
    );

    alter table if exists microposts 
       add constraint FKpdw01oqg7mb3i9rac2mbu4yrg 
       foreign key (user_id) 
       references users;

    alter table if exists password_reset_tokens 
       add constraint FKk3ndxg5xp6v7wd4gjyusp15gq 
       foreign key (user_id) 
       references users;

    alter table if exists relationships 
       add constraint FKixqgg0x8a5p2totfqe73bsqxm 
       foreign key (followed_id) 
       references users;

    alter table if exists relationships 
       add constraint FKem49n8xoiecjatiff5oiiyn4v 
       foreign key (follower_id) 
       references users;

    create table microposts (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        content varchar(140) not null,
        picture varchar(255),
        primary key (id)
    );

    create table password_reset_tokens (
        expiry_date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null unique,
        token varchar(255),
        primary key (id)
    );

    create table relationships (
        created_at timestamp(6),
        followed_id bigint not null,
        follower_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        primary key (id)
    );

    create table users (
        activated boolean,
        admin boolean not null,
        activation_at timestamp(6),
        created_at timestamp(6),
        id bigint generated by default as identity,
        refresh_token_expiration_at timestamp(6),
        reset_sent_at timestamp(6),
        updated_at timestamp(6),
        name varchar(50) not null,
        activation_digest varchar(255),
        email varchar(255) not null unique,
        password varchar(255) not null,
        refresh_token varchar(255),
        remember_digest varchar(255),
        reset_digest varchar(255),
        primary key (id)
    );

    alter table if exists microposts 
       add constraint FKpdw01oqg7mb3i9rac2mbu4yrg 
       foreign key (user_id) 
       references users;

    alter table if exists password_reset_tokens 
       add constraint FKk3ndxg5xp6v7wd4gjyusp15gq 
       foreign key (user_id) 
       references users;

    alter table if exists relationships 
       add constraint FKixqgg0x8a5p2totfqe73bsqxm 
       foreign key (followed_id) 
       references users;

    alter table if exists relationships 
       add constraint FKem49n8xoiecjatiff5oiiyn4v 
       foreign key (follower_id) 
       references users;
